app:
   test-email: javawebinar@yandex.ru

mail.async:
   corePoolSize: 8
   maxPoolSize: 8
   queueCapacity: 1000

spring:
    profiles.active: dev
    jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    thymeleaf.mode: HTML5
    mvc.favicon.enabled: false

    data.rest:
      base-path: /api
      default-page-size: 100

spring.cache:
    cache-names: group
    guava.spec: maximumSize=150,expireAfterAccess=600s

logging.level:
    ru.javaops: DEBUG
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: DEBUG