# H2 inMemory
# remote client: tcp://localhost:9092/mem:javaops

spring.jackson.serialization.indent_output: true

spring.datasource:
     url: jdbc:h2:mem:javaops
     username: sa
     password:

spring.jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate.format_sql: true

logging.level:
#   org.thymeleaf: DEBUG
   org.springframework:
      security: DEBUG
      web: DEBUG
      data: DEBUG
      http.converter: DEBUG

app:
  activation-secret-salt: test
  cache-seconds: 1
  host-url: http://localhost:8080